export type IAuthenticationDialogAction =
  'CANCEL' |
  'VIEW_LOG_IN' | 'VIEW_SIGN_UP' | 'VIEW_FORGOT_PASSWORD' | 'VIEW_ENTER_CODE' | 'VIEW_GET_HELP' |
  'SUBMIT_LOG_IN' | 'SUBMIT_SIGN_UP' | 'SUBMIT_FORGOT_PASSWORD' | 'SUBMIT_ENTER_CODE' | 'SUBMIT_GET_HELP';

